config/routes.rb
Rails.application.routes.draw do
  
  resources :stories do
    get 'zip_code', :on => :collection
  end

  get "/blog" => redirect("/blog/")

  root 'static_pages#home'

end

app/models/story.rb
class Story < ActiveRecord::Base
  
  YT_LINK_FORMAT = /^.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|\&v=)([^#\&\?]*).*/i
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

  validates         :first_name, :last_name, :street_address, :city, :state, 
                    :zip, presence: true 
  validates         :video_link, format: { with: YT_LINK_FORMAT, multiline: true }, :if => :video_link?
  validates         :email, presence: true, 
                    format: { with: VALID_EMAIL_REGEX }

  before_validation :link_validation, :on => [:create, :update], :if => :video_link?
  geocoded_by :geocode_search
  after_validation :geocode, :if => :zip_changed?

  has_attached_file :image, styles: {
    thumb: '100x100>',
    square: '200x200#',
    medium: '300x300>'
  }

  # Validate the attached image is image/jpg, image/png, etc
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  private
    def link_validation
      uid = video_link.match(YT_LINK_FORMAT)
      self.video_uid = uid[2] if uid && uid[2]
     
      if self.video_uid.to_s.length != 11
        self.errors.add(:video_link, 'is invalid.')
        false
      end
    end

    def geocode_search
      begin
        self.zip.to_region  
      rescue ArgumentError
        "Chicago, IL"
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :set_story, only: [:show, :edit, :update, :destroy]

  # GET /stories
  # GET /stories.json
  def index
    @stories = Story.all
  end

  def zip_code
    if params[:search].present?
      address = zip_to_address(params[:search])
      @stories = Story.near(address, 2)
    else
      @stories = Story.all
    end
  end

  # GET /stories/1
  # GET /stories/1.json
  def show
  end

  # GET /stories/new
  def new
    @story = Story.new
  end

  # GET /stories/1/edit
  def edit
  end

  # POST /stories
  # POST /stories.json
  def create
    @story = Story.new(story_params)

    respond_to do |format|
      if @story.save
        format.html { redirect_to stories_path, notice: 'Story was successfully created.' }
        format.json { render :index, status: :created, location: @story }
      else
        format.html { render :new }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stories/1
  # PATCH/PUT /stories/1.json
  def update
    respond_to do |format|
      if @story.update(story_params)
        format.html { redirect_to stories_path, notice: 'Story was successfully updated.' }
        format.json { render :index, status: :ok, location: @story }
      else
        format.html { render :edit }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1
  # DELETE /stories/1.json
  def destroy
    @story.destroy
    respond_to do |format|
      format.html { redirect_to stories_url, notice: 'Story was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_story
      @story = Story.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def story_params
      params.require(:story).permit(:first_name, :last_name, :street_address, :city, :state, 
                                    :email, :zip, :telephone, :story_body, :photo_id, :video_link,
                                    :image, :published)
    end

    def zip_to_address(zip)
      begin
        zip.to_region  
      rescue ArgumentError
        ""
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def youtube_embed(youtube_url)
    if youtube_url[/youtu\.be\/([^\?]*)/]
      youtube_id = $1
    else
      youtube_url[/^.*((v\/)|(embed\/)|(watch\?))\??v?=?([^\&\?]*).*/]
      youtube_id = $5
    end

    iframe = %Q{<iframe title='YouTube video player' width='400' height='250' 
              src='http://www.youtube.com/embed/#{ youtube_id }' frameborder='0' allowfullscreen></iframe>}
    iframe.html_safe
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RahmChicago</title>
  
  <!-- Youtube api -->
  <script type="text/javascript" src="https://www.google.com/jsapi"></script>
  <script type="text/javascript" src="https://www.youtube.com/iframe_api"></script>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-info alert-dismissible">
      <%= value %>
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
  <%= yield %>
</div>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<h1>Rahm for Chicago</h1>
<p>Histories</p>
<a href="/blog">Rahm for chicago Blog</a>
<a href="/stories/new">New story</a>

app/views/stories/_form.html.erb
<div class="row">
  <div class="col-xs-6 col-md-offset-3">
    <%= simple_form_for(@story) do |f| %>
        <%= render 'shared/error_messages', object: f.object%>
        <div class="row">
          <div class="col-xs-12">
            <div class="field">
              <%= f.input :first_name, required: false%>
            </div>  
          </div>
        </div>
        <div class="field">
          <%= f.input :last_name, required: false %>
        </div>
        <div class="field">
          <%= f.input :street_address, required: false %>
        </div>
        <div class="row">
          <div class="col-xs-6">
            <div class="field">
              <%= f.input :city, required: false %>
            </div>
          </div>
          <div class="col-xs-6">
            <div class="field">
              <%= f.input :state, required: false %><br>
            </div>
          </div>
        </div>
        <div class="field">
          <%= f.input :email, as: :email, required: false %>
        </div>
        <div class="row">
          <div class="col-xs-6">
            <div class="field">
              <%= f.input :zip, required: false %>
            </div>
          </div>
          <div class="col-xs-6">
            <div class="field">
              <%= f.input :telephone %>
            </div>    
          </div>
        </div>
        <div class="field">
          <%= f.input :story_body, as: :text, rows: 10, required: false %>
        </div>
        <div class="row">
          <div class="col-xs-6">
            <%= f.input :image %>
          </div>
        </div>
         <div class="field">
          <%= f.input :video_link %>
        </div>
        <div class="actions">
          <%= f.button :submit, 'Create', class: 'btn btn-primary' %>
        </div>
    <% end %>
  </div>
</div>

app/views/stories/edit.html.erb
<h1>Editing story</h1>

<%= render 'form' %>

<%= link_to 'Show', @story %> |
<%= link_to 'Back', stories_path %>

app/views/stories/index.html.erb
<%= link_to 'Search By ZipCode', zip_code_stories_path %></td>
<h1>Listing stories</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Photo</th>
      <th>Video</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stories.each do |story| %>
      <tr>
        <td><%= story.first_name %></td>
        <td><%= story.last_name %></td>
        <td><%= story.email %></td>
        <td><%= image_tag story.image.url(:square) if story.image? %></td>
        <% if story.video_link? %>
          <td>
            <div class="yt_video thumbnail">
              <a href="">
                <img src="https://img.youtube.com/vi/<%= story.video_uid %>/mqdefault.jpg" class="yt_preview img-rounded" alt= '<%= story.first_name %>' data-uid= 'stroy.video_uid'>
              </a>
            </div>
          </td>
        <% end %>
        <td><%= link_to 'Show', story %></td>
        <td><%= link_to 'Edit', edit_story_path(story) %></td>
        <td><%= link_to 'Destroy', story, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Story', new_story_path %>

app/views/stories/new.html.erb
<h1 class="text-center">New story</h1>

<%= render 'form' %>

<%= link_to 'Back', stories_path %>

app/views/stories/show.html.erb
<p>
  <strong>First name:</strong>
  <%= @story.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @story.last_name %>
</p>

<p>
  <strong>Street address:</strong>
  <%= @story.street_address %>
</p>

<p>
  <strong>City:</strong>
  <%= @story.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @story.state %>
</p>

<p>
  <strong>Email:</strong>
  <%= @story.email %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @story.zip %>
</p>

<p>
  <strong>Telephone:</strong>
  <%= @story.telephone %>
</p>

<p>
  <strong>Story body:</strong>
  <%= @story.story_body %>
</p>

<% if @story.image? %>
  <p>
    <strong>Photo:</strong>
    <%= image_tag @story.image.url(:square) %>
  </p>
<% end %>

<% if @story.video_link? %>
  <div class="row">
    <div class="video-player">
      <%= youtube_embed(@story.video_link) %>   
    </div>
  </div>  
<% end%>

<%= link_to 'Edit', edit_story_path(@story) %> |
<%= link_to 'Back', stories_path %>

app/views/stories/zip_code.html.erb
<%= link_to 'All stories', stories_path %></td>
  
<div class="container">
  <div class="row">
    <div class="row">
      <div class="col-xs-4">
        <%= form_tag zip_code_stories_path, :method => :get do %>
          <%= text_field_tag :search, params[:search] %>
          <%= submit_tag "ZipCode Search", class: 'btn btn-primary' , :name => nil %>
        <% end %>        
      </div>
    </div>
      
  </div>
  
  <% @stories.each do |story| %>
    <div class="row">
      <div class="col-xs-4">
        <h4>First Name</h4>
        <%= story.first_name %>
      </div>
      <div class="col-xs-4">
        <h4>Last Name</h4>
        <%= story.last_name %>
      </div>
      <div class="col-xs-4 zip">
        <h4>Zip Code</h4>
        <%= story.zip %>
      </div>
    </div>
  <% end %>
  
</div>